# Nginx configuration for proxying PHP requests to PHP-FPM via Unix socket

# Define the user and group for Nginx
user www-data;

# Set the number of worker processes
worker_processes auto;

# Run in foreground
daemon off;

# Error log file
error_log /dev/stdout info;

# PID file
pid /var/run/nginx/nginx.pid;

# Events block
events {
    worker_connections 1024;
}

# HTTP block
http {
    # Include MIME types
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Log format
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    # Access log file
    access_log /dev/stdout main;

    # Sendfile optimization
    sendfile on;

    # Keepalive timeout
    keepalive_timeout 65;

    # Include additional configuration files
    include /etc/nginx/conf.d/*.conf;

    # Server block for the Laravel application
    server {
        # Listen on port 80
        listen 8080;

        # Server name (replace with your domain or IP)
        server_name localhost;

        # Root directory for the Laravel application
        root /var/www/html/public;

        # Index files
        index index.php index.html index.htm;

        client_body_temp_path /tmp/nginx/body;
        client_max_body_size 200M;
        # php-status
        location /status {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass unix:/run/php/php8.1-fpm.sock;
            allow 127.0.0.1; # Restrict access to localhost for security
            deny all;
        }

        # Location block for static files
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # Location block for PHP files
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass unix:/run/php/php8.1-fpm.sock; # Proxy to PHP-FPM via Unix socket
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_buffers 16 16k;
            fastcgi_buffer_size 32k;
        }

        # Deny access to .htaccess files
        location ~ /\.ht {
            deny all;
        }

        # Error pages
        error_page 404 /index.php;
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}
